### ISSUE TITLE
Update copyright holder

### ISSUE THREAD

**Issue by juliasilge** [machow/pins-python#2]
Eventually we'll want to update this to reflect that RStudio is the copyright holder (you can see how we do this in R, [for example in the R pins](https://github.com/rstudio/pins/blob/2a1a0d89af8e9e3b696c656d5bb166502cec1ee0/DESCRIPTION#L9)):

https://github.com/machow/pins-python/blob/14982bc462f3535bef18b86a760a24a5c084a85e/docs/conf.py#L21

**Comment by machow** [comment]
Ah thanks! This file was autogenerated and I totally missed it 😬

**Comment by machow** [comment]
Alright--added a LICENSE file based on the vetiver license, and updated the docs conf.py. Do you mind double checking and closing if it looks good? :) 

https://github.com/machow/pins-python/blob/main/LICENSE

https://github.com/machow/pins-python/blob/main/docs/conf.py#L21

**Comment by juliasilge** [comment]
Looks perfect -- thank you! 🙌
