### ISSUE TITLE
Run CI across python versions 3.7+

### ISSUE THREAD

**Issue by machow** [machow/pins-python#86]
E.g. 3.7, 3.8, 3.9, 3.10

**Comment by isabelizimm** [comment]
Looks like it does not install for 3.7 :( https://github.com/tidymodels/vetiver-python/runs/6043298684?check_suite_focus=true

**Comment by machow** [comment]
It looks like for that CI run, pip is doing some intense dep resolving and going all the way back to pandas 0.22--I wonder if there's a weird conflict with another dependency (since pandas < 1.4 should support python >= 3.7.1).

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/2574498/163677962-54b22a0d-0579-4c15-bece-cea9cea6af1b.png">

**Comment by machow** [comment]
I tested using this code, and it seemed to work okay (but am still pretty stumped on why the pip resolver in the CI went back to a much earlier pandas version!)...

```
# using python 3.7 from vetiver-python repo
# pyenv local 3.7.12
pip install pip-tools
pip-compile setup.py --extra --dev --output-file=reqs.txt
pip install -r reqs.txt
```

**Comment by isabelizimm** [comment]
Hmmm...I'm curious if it's some conflicting version between vetiver and pins's versions of pandas, could [pins being a python 3.8 and up](https://github.com/machow/pins-python/blob/e7d9587fc557e2e0d9cab17fd84ccfc734f09a08/setup.cfg#L23) package be the culprit, since it seems to work on 3.8+?

**Comment by isabelizimm** [comment]
Okay, trying again but using GHA + pip-compile 👀 failing a bit more verbosely here. I think pip resolver was going so far back to console Python >3.8 and <=3.7? All should be well with versions aligned!

https://github.com/isabelizimm/vetiver-python/runs/6077398301?check_suite_focus=true

**Comment by machow** [comment]
ah thanks! I'll lower the dependency and get make some tweaks to ensure 3.7 works!

**Comment by machow** [comment]
Should be resolved by this pr!:

* #102
