### ISSUE TITLE
Complete docs home page

### ISSUE THREAD

**Issue by machow** [machow/pins-python#91]
See https://pins.rstudio.com/

**Comment by juliasilge** [comment]
When you make the home page, I would suggest using the same hex as pins for R. You can find original files at <https://github.com/rstudio/hex-stickers>.

**Comment by machow** [comment]
thanks--chucked in the logo! (can def tweak to make bigger or whatnot :)

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/2574498/163274824-cdbfa7a3-3950-425d-bf1e-caf9bdade658.png">

**Comment by juliasilge** [comment]
LOVE IT ❤️
